//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DvtForm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DVTRecruitEntities : DbContext
    {
        public DVTRecruitEntities()
            : base("name=DVTRecruitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicantContract> ApplicantContracts { get; set; }
        public virtual DbSet<ApplicantInfo> ApplicantInfoes { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<BackgroundCheck> BackgroundChecks { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<EmploymentType> EmploymentTypes { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<NextOfKin> NextOfKins { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<ProjectSynopsi> ProjectSynopsis { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<Reference> References { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
