//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DvtForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonId { get; set; }
        public string Maidenname { get; set; }
        public string Fullname { get; set; }
        public string Surname { get; set; }
        public int IdentityNumber { get; set; }
        public int GenderId { get; set; }
        public int RaceID { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string CellNumber { get; set; }
        public string HomeLanguage { get; set; }
        public string PhysicalAddress { get; set; }
        public string PostalCode { get; set; }
        public string AlternativeNumber { get; set; }
        public int UserId { get; set; }
    }
}
